import { Business } from '@/types';

export const mockBusinesses: Business[] = [
  {
    id: '1',
    name: 'Antigua Luxury Villas',
    category: 'Real Estate',
    description: 'Exclusive beachfront properties for sale and rent.',
    longDescription: 'Discover your dream home with Antigua Luxury Villas. We offer a curated selection of the finest beachfront properties, from modern apartments to sprawling estates. Our team provides unparalleled service to help you find the perfect property for your lifestyle.',
    imageUrl: 'https://picsum.photos/seed/villa/400/300',
    gallery: [
      'https://picsum.photos/seed/villa1/800/600',
      'https://picsum.photos/seed/villa2/800/600',
      'https://picsum.photos/seed/villa3/800/600',
      'https://picsum.photos/seed/villa4/800/600',
    ],
    location: "Jolly Harbour, Antigua",
    phone: "+1 (268) 555-0101",
    website: "antigualuxuryvillas.com",
    featured: true,
  },
  {
    id: '2',
    name: 'Island Cruisers Car Rental',
    category: 'Car Rentals',
    description: 'Reliable and affordable cars to explore the island.',
    longDescription: 'Explore Antigua & Barbuda at your own pace with Island Cruisers. We offer a wide range of vehicles, from compact cars for city driving to rugged SUVs for off-road adventures. All our vehicles are well-maintained and come with 24/7 roadside assistance.',
    imageUrl: 'https://picsum.photos/seed/car/400/300',
    gallery: [
      'https://picsum.photos/seed/car1/800/600',
      'https://picsum.photos/seed/car2/800/600',
      'https://picsum.photos/seed/car3/800/600',
    ],
    location: "V.C. Bird International Airport",
    phone: "+1 (268) 555-0102",
    website: "islandcruisers.ag",
  },
  {
    id: '3',
    name: 'Serenity Spa & Wellness',
    category: 'Health & Wellness',
    description: 'Rejuvenate your mind, body, and soul.',
    longDescription: 'Escape to a world of tranquility at Serenity Spa & Wellness. Our expert therapists offer a range of treatments designed to relax and rejuvenate, including massages, facials, and body wraps. We use only the finest natural and organic products.',
    imageUrl: 'https://picsum.photos/seed/spa/400/300',
    gallery: [
      'https://picsum.photos/seed/spa1/800/600',
      'https://picsum.photos/seed/spa2/800/600',
      'https://picsum.photos/seed/spa3/800/600',
      'https://picsum.photos/seed/spa4/800/600',
    ],
    location: "Dickenson Bay, Antigua",
    phone: "+1 (268) 555-0103",
    website: "serenityspaantigua.com",
    featured: true,
  },
  {
    id: '4',
    name: 'Caribbean Taste Restaurant',
    category: 'Business Listings',
    description: 'Authentic local cuisine with a modern twist.',
    longDescription: "Savor the flavors of the Caribbean at Caribbean Taste. Our menu features a delicious array of local dishes prepared with fresh, locally-sourced ingredients. Enjoy our vibrant atmosphere and friendly service for a truly memorable dining experience.",
    imageUrl: 'https://picsum.photos/seed/food/400/300',
    gallery: [
      'https://picsum.photos/seed/food1/800/600',
      'https://picsum.photos/seed/food2/800/600',
    ],
    location: "St. John's, Antigua",
    phone: "+1 (268) 555-0104",
    website: "caribbeantaste.ag",
    featured: true,
  },
  {
    id: '5',
    name: 'Paradise Properties AG',
    category: 'Real Estate',
    description: 'Your key to paradise. Commercial and residential properties.',
    longDescription: 'Paradise Properties AG is your trusted partner in Antiguan real estate. Whether you are looking for a family home, a vacation rental, or a commercial investment, our experienced agents are here to guide you every step of the way.',
    imageUrl: 'https://picsum.photos/seed/property/400/300',
    gallery: [
      'https://picsum.photos/seed/prop1/800/600',
      'https://picsum.photos/seed/prop2/800/600',
      'https://picsum.photos/seed/prop3/800/600',
    ],
    location: "English Harbour, Antigua",
    phone: "+1 (268) 555-0105",
    website: "paradiseproperties.ag",
  },
  {
    id: '6',
    name: 'Adventure Antigua Tours',
    category: 'Business Listings',
    description: 'Eco-tours and snorkeling adventures.',
    longDescription: 'Experience the natural beauty of Antigua with Adventure Antigua Tours. We offer a variety of eco-tours, including snorkeling trips, kayaking adventures, and guided hikes. Our knowledgeable guides will show you the best of the island\'s hidden gems.',
    imageUrl: 'https://picsum.photos/seed/tour/400/300',
    gallery: [
      'https://picsum.photos/seed/tour1/800/600',
      'https://picsum.photos/seed/tour2/800/600',
      'https://picsum.photos/seed/tour3/800/600',
    ],
    location: "Falmouth Harbour, Antigua",
    phone: "+1 (268) 555-0106",
    website: "adventureantigua.com",
    featured: true,
  },
];
